# Generated by Django 6.1.1 on 2026-09-14 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm', models.CharField(choices=[('blackrock', 'BlackRock'), ('jpmorgan', 'JPMorgan')], max_length=16)),
                ('title', models.CharField(max_length=500)),
                ('published_date', models.DateField(help_text='Date the source published the piece')),
                ('report_type', models.CharField(choices=[('quarterly_outlook', 'Quarterly outlook'), ('yearly_forecast', 'Yearly forecast'), ('weekly_commentary', 'Weekly commentary'), ('research_note', 'Research note')], default='research_note', max_length=24)),
                ('short_summary', models.TextField(blank=True, help_text='A few-sentence extracted takeaway (deck/subheading or first substantive paragraph) — not the full article.')),
                ('source_url', models.URLField(help_text='Canonical link to the full piece; dedupe key.', max_length=1000, unique=True)),
                ('fetched_at', models.DateTimeField(auto_now=True, help_text='When our scraper last pulled/updated this row.')),
            ],
            options={
                'ordering': ['-published_date', '-fetched_at'],
            },
        ),
    ]
