# Generated by Django 6.1.1 on 2026-09-14 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperInvestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Well-known investor, e.g. 'Warren Buffett'", max_length=128)),
                ('fund_name', models.CharField(help_text="Filing entity, e.g. 'Berkshire Hathaway Inc'", max_length=255)),
                ('cik', models.CharField(help_text='SEC Central Index Key, zero-padded to 10 digits', max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether to keep pulling new filings for this filer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusip', models.CharField(db_index=True, max_length=9)),
                ('issuer_name', models.CharField(max_length=255)),
                ('ticker', models.CharField(blank=True, db_index=True, help_text='Best-effort resolved ticker; 13F only reports CUSIP so this can be blank', max_length=16)),
                ('shares', models.BigIntegerField(default=0)),
                ('market_value', models.BigIntegerField(default=0, help_text='Reported position value in USD')),
                ('filing_quarter', models.DateField(help_text='Quarter-end date this holding was reported as of (e.g. 2025-06-30)')),
                ('filed_date', models.DateField(help_text='Date the 13F-HR was actually filed with the SEC (~45 days after quarter end)')),
                ('accession_number', models.CharField(blank=True, help_text='SEC EDGAR accession number of the source filing', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='super_investors.superinvestor')),
            ],
            options={
                'ordering': ['-filing_quarter', 'investor', '-market_value'],
                'indexes': [models.Index(fields=['investor', 'cusip', 'filing_quarter'], name='super_inves_investo_adf252_idx')],
                'constraints': [models.UniqueConstraint(fields=('investor', 'cusip', 'filing_quarter'), name='uniq_holding_per_quarter')],
            },
        ),
    ]
