# Generated by Django 6.1.1 on 2026-09-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_investors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='current_price',
            field=models.FloatField(blank=True, help_text="Live market price as of the last `update_current_prices` run (mark-to-market for unrealized P/L); null until computed or if the ticker can't be resolved", null=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='current_price_as_of',
            field=models.DateTimeField(blank=True, help_text='When current_price was last fetched', null=True),
        ),
    ]
