# Generated by Django 6.1.1 on 2026-09-14 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=16)),
                ('headline_line', models.CharField(help_text="Terse, action/impact-oriented one-liner: 'TICKER: what happened -> why it matters'", max_length=280)),
                ('sentiment', models.CharField(choices=[('bullish', 'Bullish'), ('bearish', 'Bearish'), ('neutral', 'Neutral')], default='neutral', max_length=8)),
                ('sentiment_score', models.FloatField(blank=True, help_text='Raw Alpha Vantage ticker_sentiment_score, -1 (bearish) .. 1 (bullish)', null=True)),
                ('relevance_score', models.FloatField(help_text='Alpha Vantage per-ticker relevance_score, 0..1')),
                ('source', models.CharField(blank=True, max_length=128)),
                ('source_url', models.URLField(max_length=1000)),
                ('published_at', models.DateTimeField(help_text='When the source article was published')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at', '-relevance_score'],
                'indexes': [models.Index(fields=['ticker', '-published_at'], name='market_news_ticker_135da7_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_url', 'ticker'), name='uniq_news_item')],
            },
        ),
    ]
