# Generated by Django 6.1.1 on 2026-09-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CongressTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('politician_name', models.CharField(db_index=True, max_length=128)),
                ('party', models.CharField(choices=[('D', 'Democrat'), ('R', 'Republican'), ('I', 'Independent'), ('?', 'Unknown')], default='?', max_length=1)),
                ('chamber', models.CharField(choices=[('House', 'House'), ('Senate', 'Senate')], db_index=True, max_length=6)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('ticker', models.CharField(blank=True, db_index=True, help_text='Ticker symbol, blank for non-traded assets (e.g. private funds)', max_length=12)),
                ('asset_description', models.CharField(help_text='Asset name as printed on the disclosure', max_length=255)),
                ('transaction_type', models.CharField(choices=[('buy', 'Purchase'), ('sell', 'Sale'), ('exchange', 'Exchange')], max_length=8)),
                ('amount_min', models.IntegerField()),
                ('amount_max', models.IntegerField()),
                ('transaction_date', models.DateField(help_text='Date the member actually made the trade')),
                ('disclosure_date', models.DateField(help_text='Date the trade was publicly disclosed (lags transaction_date)')),
                ('filing_url', models.URLField(blank=True, help_text='Link to the source filing (PDF)', max_length=500)),
                ('source_doc_id', models.CharField(blank=True, help_text='Filing id from the source system, for traceability', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-disclosure_date', '-transaction_date'],
                'indexes': [models.Index(fields=['disclosure_date'], name='congress_tr_disclos_51d12d_idx'), models.Index(fields=['transaction_date'], name='congress_tr_transac_7aaa3f_idx')],
                'constraints': [models.UniqueConstraint(fields=('chamber', 'source_doc_id', 'ticker', 'transaction_date', 'transaction_type', 'amount_min', 'amount_max'), name='uniq_congress_trade_row')],
            },
        ),
    ]
