# Generated by Django 6.1.1 on 2026-09-14 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress_trades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='congresstrade',
            name='matched_trade',
            field=models.ForeignKey(blank=True, help_text='The FIFO-paired buy/sell row this round-trip was closed against', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_by', to='congress_trades.congresstrade'),
        ),
        migrations.AddField(
            model_name='congresstrade',
            name='profit_kind',
            field=models.CharField(blank=True, choices=[('realized', 'Realized (closed round-trip)'), ('unrealized', 'Unrealized (still open, marked to market)')], max_length=10),
        ),
        migrations.AddField(
            model_name='congresstrade',
            name='realized_profit',
            field=models.FloatField(blank=True, help_text='Estimated $ profit once this position was closed by a matching sale (FIFO)', null=True),
        ),
        migrations.AddField(
            model_name='congresstrade',
            name='unrealized_profit',
            field=models.FloatField(blank=True, help_text='Estimated $ profit marking this still-open buy to the latest market price', null=True),
        ),
    ]
