# Generated by Django 6.1.1 on 2026-09-12 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peer', models.CharField(help_text='Telegram peer id, e.g. -1001845341480', max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('short', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuantityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('default', 'Default'), ('symbol', 'By symbol'), ('group', 'By group')], max_length=8)),
                ('key', models.CharField(blank=True, help_text='Symbol or peer id (empty for default)', max_length=64)),
                ('qty', models.IntegerField(default=1)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scope', 'key'), name='uniq_qty_rule')],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('kind', models.CharField(blank=True, max_length=16)),
                ('ltp', models.FloatField(blank=True, null=True)),
                ('asof', models.CharField(blank=True, max_length=64)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='traderacker.channel')),
            ],
            options={
                'ordering': ['symbol'],
                'constraints': [models.UniqueConstraint(fields=('channel', 'symbol'), name='uniq_quote')],
            },
        ),
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.BigIntegerField(help_text='Telegram message id')),
                ('day_label', models.CharField(blank=True, max_length=32)),
                ('text', models.TextField()),
                ('ts', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='traderacker.channel')),
            ],
            options={
                'ordering': ['-ts'],
                'constraints': [models.UniqueConstraint(fields=('channel', 'mid'), name='uniq_message')],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('trade', models.CharField(help_text="Instrument, e.g. 'NIFTY 23900 PE'", max_length=255)),
                ('direction', models.CharField(blank=True, max_length=32)),
                ('entry', models.FloatField(blank=True, null=True)),
                ('target', models.FloatField(blank=True, null=True)),
                ('stop_loss', models.FloatField(blank=True, null=True)),
                ('ltp_exit', models.FloatField(blank=True, null=True)),
                ('unrealized', models.FloatField(blank=True, null=True)),
                ('realized', models.FloatField(blank=True, null=True)),
                ('cumulative', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=8)),
                ('note', models.TextField(blank=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='traderacker.channel')),
            ],
            options={
                'ordering': ['date', 'id'],
                'constraints': [models.UniqueConstraint(fields=('channel', 'date', 'trade', 'entry', 'status'), name='uniq_trade_row')],
            },
        ),
    ]
