# Generated by Django 6.1.1 on 2026-09-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traderacker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='posted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the Telegram message that announced this trade', null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='source_mid',
            field=models.BigIntegerField(blank=True, help_text='Telegram message id this trade was parsed from', null=True),
        ),
    ]
