# Generated by Django 6.1.1 on 2026-09-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traderacker', '0002_trade_posted_at_trade_source_mid'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='asset_class',
            field=models.CharField(choices=[('stock', 'Stocks'), ('option', 'Options'), ('index', 'Index'), ('crypto', 'Crypto'), ('metal', 'Metals'), ('commodity', 'Oil & Commodities'), ('forex', 'Forex'), ('other', 'Other')], db_index=True, default='other', max_length=12),
        ),
        migrations.AddField(
            model_name='trade',
            name='peak_profit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
