# Generated by Django 6.1.1 on 2026-09-13 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traderacker', '0003_trade_asset_class_trade_peak_profit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='style',
            field=models.CharField(choices=[('auto', 'Auto-detect'), ('options', 'Options-first (@ premium)'), ('cash', 'Cash equity (Buy X above N)'), ('crypto', 'Crypto futures (LONG/SHORT Nx)'), ('mixed', 'Mixed multi-asset'), ('promo', 'Mostly promo/news (skip)')], default='auto', help_text="Consumer's typical posting style, drives parsing", max_length=12),
        ),
        migrations.AddField(
            model_name='channel',
            name='style_notes',
            field=models.TextField(blank=True, help_text="Free-text notes on this consumer's format for easier parsing"),
        ),
        migrations.CreateModel(
            name='PaperTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=64)),
                ('asset_class', models.CharField(choices=[('stock', 'Stocks'), ('option', 'Options'), ('index', 'Index'), ('crypto', 'Crypto'), ('metal', 'Metals'), ('commodity', 'Oil & Commodities'), ('forex', 'Forex'), ('other', 'Other')], default='stock', max_length=12)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', max_length=4)),
                ('notional_inr', models.PositiveIntegerField(default=10000)),
                ('entry_price', models.FloatField()),
                ('price_source', models.CharField(blank=True, choices=[('yahoo', 'Yahoo'), ('dhan', 'Dhan'), ('posted', 'Consumer posted'), ('manual', 'Manual')], default='posted', max_length=8)),
                ('current_price', models.FloatField(blank=True, null=True)),
                ('highest_price', models.FloatField(blank=True, null=True)),
                ('lowest_price', models.FloatField(blank=True, null=True)),
                ('stop_loss_pct', models.FloatField(default=20.0)),
                ('trailing_pct', models.FloatField(default=20.0)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], db_index=True, default='Open', max_length=8)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('realized_pct', models.FloatField(blank=True, null=True)),
                ('realized_inr', models.FloatField(blank=True, null=True)),
                ('consumer_claimed_pct', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, help_text="1.0 if consumer's claimed direction matched market outcome", null=True)),
                ('is_manual', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('source_trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_trades', to='traderacker.trade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_paper', models.BooleanField(default=True, help_text='Auto-open paper trades from consumer signals')),
                ('capital_per_trade', models.PositiveIntegerField(default=10000, help_text='Fixed ₹ notional per paper trade')),
                ('stop_loss_pct', models.FloatField(default=20.0)),
                ('trailing_pct', models.FloatField(default=20.0)),
                ('auto_consumers', models.ManyToManyField(blank=True, help_text='Consumers whose signals auto-open paper trades (top-10 default)', related_name='auto_pref_users', to='traderacker.channel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
