# Generated by Django 6.1.1 on 2026-09-14 02:05, hand-edited to migrate
# Quote.asof from a free-text CharField to a real DateTimeField without
# crashing on legacy garbage/unparseable strings.
#
# Approach: add a new nullable DateTimeField, best-effort parse every
# existing string value into it (unparseable/blank values -> NULL, counted
# and reported rather than raising), drop the old CharField, then rename the
# new field into its place.
import datetime as dt
import re

from django.db import migrations, models
from django.utils import timezone as dj_timezone
from django.utils.dateparse import parse_datetime

# same trailing tz-label stripper as import_legacy_data.as_asof_datetime
# (e.g. "2026-09-13 00:12 IST" -> "2026-09-13 00:12")
_ASOF_TZ_SUFFIX = re.compile(r'\s+[A-Za-z]{2,5}$')


def _parse_asof(s):
    """Best-effort parse of a legacy 'asof' string into an aware datetime.
    Returns None (never raises) for empty/unparseable values."""
    if not s:
        return None
    s = str(s).strip()
    if not s:
        return None
    parsed = parse_datetime(s)
    if parsed is None:
        stripped = _ASOF_TZ_SUFFIX.sub('', s)
        parsed = parse_datetime(stripped) or parse_datetime(stripped.replace(' ', 'T'))
    if parsed is None:
        try:
            parsed = dt.datetime.fromisoformat(s[:19])
        except ValueError:
            return None
    if dj_timezone.is_naive(parsed):
        parsed = dj_timezone.make_aware(parsed)
    return parsed


def forwards_populate(apps, schema_editor):
    Quote = apps.get_model('traderacker', 'Quote')
    total = parsed_ok = blank = unparsed = 0
    for q in Quote.objects.all().iterator():
        total += 1
        raw = q.asof
        if not raw or not str(raw).strip():
            blank += 1
            q.asof_dt = None
        else:
            dt_val = _parse_asof(raw)
            if dt_val is None:
                unparsed += 1
                print(f"  [quote_asof_datetime] Quote id={q.pk} symbol={q.symbol!r} "
                      f"unparsable asof={raw!r} -> NULL")
            else:
                parsed_ok += 1
            q.asof_dt = dt_val
        q.save(update_fields=['asof_dt'])
    print(f"[quote_asof_datetime] Quote.asof migration: {total} rows total, "
          f"{parsed_ok} parsed, {blank} blank -> NULL, {unparsed} unparsable -> NULL")


def backwards_populate(apps, schema_editor):
    Quote = apps.get_model('traderacker', 'Quote')
    for q in Quote.objects.all().iterator():
        q.asof = q.asof_dt.isoformat() if q.asof_dt else ''
        q.save(update_fields=['asof'])


class Migration(migrations.Migration):

    dependencies = [
        ('traderacker', '0005_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='asof_dt',
            field=models.DateTimeField(
                blank=True, null=True,
                help_text='When this quote was fetched from the market provider'),
        ),
        migrations.RunPython(forwards_populate, backwards_populate),
        migrations.RemoveField(
            model_name='quote',
            name='asof',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='asof_dt',
            new_name='asof',
        ),
    ]
