# Generated by Django 6.1.1 on 2026-09-14 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traderacker', '0009_nirmal_bang_official_style'),
        ('traderacker', '0009_options_train_style'),
    ]

    operations = [
    ]
