# Generated by Django 6.1.1 on 2026-09-14 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traderacker', '0009_serezha_calls_style'),
        ('traderacker', '0010_merge_20260914_0923'),
    ]

    operations = [
    ]
