# Generated by Django 6.1.1 on 2026-09-14 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traderacker', '0009_stockpro_online_style'),
        ('traderacker', '0011_merge_20260914_0925'),
    ]

    operations = [
    ]
