# Generated by Django 6.1.1 on 2026-09-14 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traderacker', '0009_stock_thunder_style'),
        ('traderacker', '0012_merge_20260914_0927'),
    ]

    operations = [
    ]
