# Generated by Django 6.1.1 on 2026-09-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traderacker', '0014_stockpro_online_ladder_shape_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertrade',
            name='profit_target_pct',
            field=models.FloatField(default=50.0, help_text='Close outright once unrealized profit reaches this %'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='profit_target_pct',
            field=models.FloatField(default=50.0, help_text='Close a paper trade outright once unrealized profit reaches this %'),
        ),
    ]
