# Generated by Django 6.1.1 on 2026-09-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traderacker', '0015_papertrade_profit_target_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertrade',
            name='max_hold_days',
            field=models.PositiveIntegerField(default=60, help_text='Force-close after this many days, regardless of price'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='max_hold_days',
            field=models.PositiveIntegerField(default=60, help_text='Force-close a paper trade after this many days, regardless of price'),
        ),
    ]
