# Generated by Django 6.1.1 on 2026-09-14 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traderacker', '0016_papertrade_max_hold_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedProfitEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.BigIntegerField(help_text='Telegram message id')),
                ('kind', models.CharField(choices=[('profit', 'Profit'), ('exit_price', 'Exit price')], max_length=16)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='traderacker.channel')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('channel', 'mid', 'kind'), name='uniq_processed_profit_event')],
            },
        ),
    ]
