# Generated by Django 6.1.1 on 2026-09-15 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traderacker', '0014_batch1_channel_styles'),
        ('traderacker', '0028_batch7_vizu_style'),
    ]

    operations = [
    ]
