# Generated by Django 6.1.1 on 2026-09-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traderacker', '0031_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='manually_edited',
            field=models.BooleanField(default=False, help_text='Set automatically when an admin edits this row inline -- mark_live/close_eod refuse to touch it after that, so a manual correction sticks instead of getting overwritten by the next automated pass.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='kind',
            field=models.CharField(choices=[('target_hit', 'Target hit'), ('stop_loss_hit', 'Stop-loss hit'), ('eod_close', 'Squared off at close')], max_length=20),
        ),
    ]
