# Generated by Django 6.1.1 on 2026-09-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traderacker', '0032_trade_manually_edited_alter_event_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='strike',
            field=models.FloatField(blank=True, help_text='Numeric strike price for options; null for non-options', null=True),
        ),
    ]
