# Generated by Django 6.1.1 on 2026-09-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traderacker', '0033_trade_strike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedprofitevent',
            name='kind',
            field=models.CharField(choices=[('profit', 'Profit'), ('exit_price', 'Exit price'), ('llm_triage', 'LLM triage')], max_length=16),
        ),
    ]
